# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/applications/interchain_accounts/controller/v1/tx.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from x.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from ibc.applications.interchain_accounts.v1 import packet_pb2 as ibc_dot_applications_dot_interchain__accounts_dot_v1_dot_packet__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;ibc/applications/interchain_accounts/controller/v1/tx.proto\x12\x32ibc.applications.interchain_accounts.controller.v1\x1a\x14gogoproto/gogo.proto\x1a\x34ibc/applications/interchain_accounts/v1/packet.proto\"y\n\x1cMsgRegisterInterchainAccount\x12\r\n\x05owner\x18\x01 \x01(\t\x12/\n\rconnection_id\x18\x02 \x01(\tB\x18\xf2\xde\x1f\x14yaml:\"connection_id\"\x12\x0f\n\x07version\x18\x03 \x01(\t:\x08\xe8\xa0\x1f\x00\x88\xa0\x1f\x00\"Q\n$MsgRegisterInterchainAccountResponse\x12)\n\nchannel_id\x18\x01 \x01(\tB\x15\xf2\xde\x1f\x11yaml:\"channel_id\"\"\x83\x02\n\tMsgSendTx\x12\r\n\x05owner\x18\x01 \x01(\t\x12/\n\rconnection_id\x18\x02 \x01(\tB\x18\xf2\xde\x1f\x14yaml:\"connection_id\"\x12u\n\x0bpacket_data\x18\x03 \x01(\x0b\x32\x44.ibc.applications.interchain_accounts.v1.InterchainAccountPacketDataB\x1a\xf2\xde\x1f\x12yaml:\"packet_data\"\xc8\xde\x1f\x00\x12\x35\n\x10relative_timeout\x18\x04 \x01(\x04\x42\x1b\xf2\xde\x1f\x17yaml:\"relative_timeout\":\x08\xe8\xa0\x1f\x00\x88\xa0\x1f\x00\"%\n\x11MsgSendTxResponse\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x32\xe0\x02\n\x03Msg\x12\xc7\x01\n\x19RegisterInterchainAccount\x12P.ibc.applications.interchain_accounts.controller.v1.MsgRegisterInterchainAccount\x1aX.ibc.applications.interchain_accounts.controller.v1.MsgRegisterInterchainAccountResponse\x12\x8e\x01\n\x06SendTx\x12=.ibc.applications.interchain_accounts.controller.v1.MsgSendTx\x1a\x45.ibc.applications.interchain_accounts.controller.v1.MsgSendTxResponseBRZPgithub.com/cosmos/ibc-go/v6/modules/apps/27-interchain-accounts/controller/typesb\x06proto3')



_MSGREGISTERINTERCHAINACCOUNT = DESCRIPTOR.message_types_by_name['MsgRegisterInterchainAccount']
_MSGREGISTERINTERCHAINACCOUNTRESPONSE = DESCRIPTOR.message_types_by_name['MsgRegisterInterchainAccountResponse']
_MSGSENDTX = DESCRIPTOR.message_types_by_name['MsgSendTx']
_MSGSENDTXRESPONSE = DESCRIPTOR.message_types_by_name['MsgSendTxResponse']
MsgRegisterInterchainAccount = _reflection.GeneratedProtocolMessageType('MsgRegisterInterchainAccount', (_message.Message,), {
  'DESCRIPTOR' : _MSGREGISTERINTERCHAINACCOUNT,
  '__module__' : 'ibc.applications.interchain_accounts.controller.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:ibc.applications.interchain_accounts.controller.v1.MsgRegisterInterchainAccount)
  })
_sym_db.RegisterMessage(MsgRegisterInterchainAccount)

MsgRegisterInterchainAccountResponse = _reflection.GeneratedProtocolMessageType('MsgRegisterInterchainAccountResponse', (_message.Message,), {
  'DESCRIPTOR' : _MSGREGISTERINTERCHAINACCOUNTRESPONSE,
  '__module__' : 'ibc.applications.interchain_accounts.controller.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:ibc.applications.interchain_accounts.controller.v1.MsgRegisterInterchainAccountResponse)
  })
_sym_db.RegisterMessage(MsgRegisterInterchainAccountResponse)

MsgSendTx = _reflection.GeneratedProtocolMessageType('MsgSendTx', (_message.Message,), {
  'DESCRIPTOR' : _MSGSENDTX,
  '__module__' : 'ibc.applications.interchain_accounts.controller.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:ibc.applications.interchain_accounts.controller.v1.MsgSendTx)
  })
_sym_db.RegisterMessage(MsgSendTx)

MsgSendTxResponse = _reflection.GeneratedProtocolMessageType('MsgSendTxResponse', (_message.Message,), {
  'DESCRIPTOR' : _MSGSENDTXRESPONSE,
  '__module__' : 'ibc.applications.interchain_accounts.controller.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:ibc.applications.interchain_accounts.controller.v1.MsgSendTxResponse)
  })
_sym_db.RegisterMessage(MsgSendTxResponse)

_MSG = DESCRIPTOR.services_by_name['Msg']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZPgithub.com/cosmos/ibc-go/v6/modules/apps/27-interchain-accounts/controller/types'
  _MSGREGISTERINTERCHAINACCOUNT.fields_by_name['connection_id']._options = None
  _MSGREGISTERINTERCHAINACCOUNT.fields_by_name['connection_id']._serialized_options = b'\362\336\037\024yaml:\"connection_id\"'
  _MSGREGISTERINTERCHAINACCOUNT._options = None
  _MSGREGISTERINTERCHAINACCOUNT._serialized_options = b'\350\240\037\000\210\240\037\000'
  _MSGREGISTERINTERCHAINACCOUNTRESPONSE.fields_by_name['channel_id']._options = None
  _MSGREGISTERINTERCHAINACCOUNTRESPONSE.fields_by_name['channel_id']._serialized_options = b'\362\336\037\021yaml:\"channel_id\"'
  _MSGSENDTX.fields_by_name['connection_id']._options = None
  _MSGSENDTX.fields_by_name['connection_id']._serialized_options = b'\362\336\037\024yaml:\"connection_id\"'
  _MSGSENDTX.fields_by_name['packet_data']._options = None
  _MSGSENDTX.fields_by_name['packet_data']._serialized_options = b'\362\336\037\022yaml:\"packet_data\"\310\336\037\000'
  _MSGSENDTX.fields_by_name['relative_timeout']._options = None
  _MSGSENDTX.fields_by_name['relative_timeout']._serialized_options = b'\362\336\037\027yaml:\"relative_timeout\"'
  _MSGSENDTX._options = None
  _MSGSENDTX._serialized_options = b'\350\240\037\000\210\240\037\000'
  _MSGREGISTERINTERCHAINACCOUNT._serialized_start=191
  _MSGREGISTERINTERCHAINACCOUNT._serialized_end=312
  _MSGREGISTERINTERCHAINACCOUNTRESPONSE._serialized_start=314
  _MSGREGISTERINTERCHAINACCOUNTRESPONSE._serialized_end=395
  _MSGSENDTX._serialized_start=398
  _MSGSENDTX._serialized_end=657
  _MSGSENDTXRESPONSE._serialized_start=659
  _MSGSENDTXRESPONSE._serialized_end=696
  _MSG._serialized_start=699
  _MSG._serialized_end=1051
# @@protoc_insertion_point(module_scope)
