# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fx/other/query.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from x.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from x.google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from x.cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66x/other/query.proto\x12\x08\x66x.other\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\"\x11\n\x0fGasPriceRequest\"\x88\x01\n\x10GasPriceResponse\x12t\n\ngas_prices\x18\x01 \x03(\x0b\x32\x19.cosmos.base.v1beta1.CoinBE\xc8\xde\x1f\x00\xaa\xdf\x1f(github.com/cosmos/cosmos-sdk/types.Coins\xf2\xde\x1f\x11yaml:\"gas_prices\"2g\n\x05Query\x12^\n\x08GasPrice\x12\x19.fx.other.GasPriceRequest\x1a\x1a.fx.other.GasPriceResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/fx/other/gas_priceB,Z*github.com/functionx/fx-core/x/other/typesb\x06proto3')



_GASPRICEREQUEST = DESCRIPTOR.message_types_by_name['GasPriceRequest']
_GASPRICERESPONSE = DESCRIPTOR.message_types_by_name['GasPriceResponse']
GasPriceRequest = _reflection.GeneratedProtocolMessageType('GasPriceRequest', (_message.Message,), {
  'DESCRIPTOR' : _GASPRICEREQUEST,
  '__module__' : 'fx.other.query_pb2'
  # @@protoc_insertion_point(class_scope:fx.other.GasPriceRequest)
  })
_sym_db.RegisterMessage(GasPriceRequest)

GasPriceResponse = _reflection.GeneratedProtocolMessageType('GasPriceResponse', (_message.Message,), {
  'DESCRIPTOR' : _GASPRICERESPONSE,
  '__module__' : 'fx.other.query_pb2'
  # @@protoc_insertion_point(class_scope:fx.other.GasPriceResponse)
  })
_sym_db.RegisterMessage(GasPriceResponse)

_QUERY = DESCRIPTOR.services_by_name['Query']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z*github.com/functionx/fx-core/x/other/types'
  _GASPRICERESPONSE.fields_by_name['gas_prices']._options = None
  _GASPRICERESPONSE.fields_by_name['gas_prices']._serialized_options = b'\310\336\037\000\252\337\037(github.com/cosmos/cosmos-sdk/types.Coins\362\336\037\021yaml:\"gas_prices\"'
  _QUERY.methods_by_name['GasPrice']._options = None
  _QUERY.methods_by_name['GasPrice']._serialized_options = b'\202\323\344\223\002\025\022\023/fx/other/gas_price'
  _GASPRICEREQUEST._serialized_start=118
  _GASPRICEREQUEST._serialized_end=135
  _GASPRICERESPONSE._serialized_start=138
  _GASPRICERESPONSE._serialized_end=274
  _QUERY._serialized_start=276
  _QUERY._serialized_end=379
# @@protoc_insertion_point(module_scope)
