# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fx/ibc/applications/transfer/v1/transfer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.fx/ibc/applications/transfer/v1/transfer.proto\x12\x1f\x66x.ibc.applications.transfer.v1\"\x85\x01\n\x17\x46ungibleTokenPacketData\x12\r\n\x05\x64\x65nom\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\t\x12\x0e\n\x06sender\x18\x03 \x01(\t\x12\x10\n\x08receiver\x18\x04 \x01(\t\x12\x0e\n\x06router\x18\x05 \x01(\t\x12\x0b\n\x03\x66\x65\x65\x18\x06 \x01(\t\x12\x0c\n\x04memo\x18\x07 \x01(\tB@Z>github.com/functionx/fx-core/x/ibc/applications/transfer/typesb\x06proto3')



_FUNGIBLETOKENPACKETDATA = DESCRIPTOR.message_types_by_name['FungibleTokenPacketData']
FungibleTokenPacketData = _reflection.GeneratedProtocolMessageType('FungibleTokenPacketData', (_message.Message,), {
  'DESCRIPTOR' : _FUNGIBLETOKENPACKETDATA,
  '__module__' : 'fx.ibc.applications.transfer.v1.transfer_pb2'
  # @@protoc_insertion_point(class_scope:fx.ibc.applications.transfer.v1.FungibleTokenPacketData)
  })
_sym_db.RegisterMessage(FungibleTokenPacketData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z>github.com/functionx/fx-core/x/ibc/applications/transfer/types'
  _FUNGIBLETOKENPACKETDATA._serialized_start=84
  _FUNGIBLETOKENPACKETDATA._serialized_end=217
# @@protoc_insertion_point(module_scope)
