# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fx/ibc/applications/transfer/v1/transfer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from x.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.fx/ibc/applications/transfer/v1/transfer.proto\x12\x1f\x66x.ibc.applications.transfer.v1\x1a\x14gogoproto/gogo.proto\"w\n\x17\x46ungibleTokenPacketData\x12\r\n\x05\x64\x65nom\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\t\x12\x0e\n\x06sender\x18\x03 \x01(\t\x12\x10\n\x08receiver\x18\x04 \x01(\t\x12\x0e\n\x06router\x18\x05 \x01(\t\x12\x0b\n\x03\x66\x65\x65\x18\x06 \x01(\t\".\n\nDenomTrace\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x12\n\nbase_denom\x18\x02 \x01(\t\"l\n\x06Params\x12-\n\x0csend_enabled\x18\x01 \x01(\x08\x42\x17\xf2\xde\x1f\x13yaml:\"send_enabled\"\x12\x33\n\x0freceive_enabled\x18\x02 \x01(\x08\x42\x1a\xf2\xde\x1f\x16yaml:\"receive_enabled\"B@Z>github.com/functionx/fx-core/x/ibc/applications/transfer/typesb\x06proto3')



_FUNGIBLETOKENPACKETDATA = DESCRIPTOR.message_types_by_name['FungibleTokenPacketData']
_DENOMTRACE = DESCRIPTOR.message_types_by_name['DenomTrace']
_PARAMS = DESCRIPTOR.message_types_by_name['Params']
FungibleTokenPacketData = _reflection.GeneratedProtocolMessageType('FungibleTokenPacketData', (_message.Message,), {
  'DESCRIPTOR' : _FUNGIBLETOKENPACKETDATA,
  '__module__' : 'fx.ibc.applications.transfer.v1.transfer_pb2'
  # @@protoc_insertion_point(class_scope:fx.ibc.applications.transfer.v1.FungibleTokenPacketData)
  })
_sym_db.RegisterMessage(FungibleTokenPacketData)

DenomTrace = _reflection.GeneratedProtocolMessageType('DenomTrace', (_message.Message,), {
  'DESCRIPTOR' : _DENOMTRACE,
  '__module__' : 'fx.ibc.applications.transfer.v1.transfer_pb2'
  # @@protoc_insertion_point(class_scope:fx.ibc.applications.transfer.v1.DenomTrace)
  })
_sym_db.RegisterMessage(DenomTrace)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), {
  'DESCRIPTOR' : _PARAMS,
  '__module__' : 'fx.ibc.applications.transfer.v1.transfer_pb2'
  # @@protoc_insertion_point(class_scope:fx.ibc.applications.transfer.v1.Params)
  })
_sym_db.RegisterMessage(Params)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z>github.com/functionx/fx-core/x/ibc/applications/transfer/types'
  _PARAMS.fields_by_name['send_enabled']._options = None
  _PARAMS.fields_by_name['send_enabled']._serialized_options = b'\362\336\037\023yaml:\"send_enabled\"'
  _PARAMS.fields_by_name['receive_enabled']._options = None
  _PARAMS.fields_by_name['receive_enabled']._serialized_options = b'\362\336\037\026yaml:\"receive_enabled\"'
  _FUNGIBLETOKENPACKETDATA._serialized_start=105
  _FUNGIBLETOKENPACKETDATA._serialized_end=224
  _DENOMTRACE._serialized_start=226
  _DENOMTRACE._serialized_end=272
  _PARAMS._serialized_start=274
  _PARAMS._serialized_end=382
# @@protoc_insertion_point(module_scope)
