# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from fxsdk.x.marginx.oracle.v1 import query_pb2 as marginx_dot_oracle_dot_v1_dot_query__pb2


class QueryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Markets = channel.unary_unary(
                '/marginx.oracle.v1.Query/Markets',
                request_serializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryMarketsRequest.SerializeToString,
                response_deserializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryMarketsResponse.FromString,
                )
        self.Market = channel.unary_unary(
                '/marginx.oracle.v1.Query/Market',
                request_serializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryMarketRequest.SerializeToString,
                response_deserializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryMarketResponse.FromString,
                )
        self.Price = channel.unary_unary(
                '/marginx.oracle.v1.Query/Price',
                request_serializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryPriceRequest.SerializeToString,
                response_deserializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryPriceResponse.FromString,
                )
        self.Prices = channel.unary_unary(
                '/marginx.oracle.v1.Query/Prices',
                request_serializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryPricesRequest.SerializeToString,
                response_deserializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryPricesResponse.FromString,
                )
        self.Params = channel.unary_unary(
                '/marginx.oracle.v1.Query/Params',
                request_serializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryParamsRequest.SerializeToString,
                response_deserializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryParamsResponse.FromString,
                )
        self.Aggregators = channel.unary_unary(
                '/marginx.oracle.v1.Query/Aggregators',
                request_serializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryAggregatorsRequest.SerializeToString,
                response_deserializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryAggregatorsResponse.FromString,
                )


class QueryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Markets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Market(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Price(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Params(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Aggregators(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Markets': grpc.unary_unary_rpc_method_handler(
                    servicer.Markets,
                    request_deserializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryMarketsRequest.FromString,
                    response_serializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryMarketsResponse.SerializeToString,
            ),
            'Market': grpc.unary_unary_rpc_method_handler(
                    servicer.Market,
                    request_deserializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryMarketRequest.FromString,
                    response_serializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryMarketResponse.SerializeToString,
            ),
            'Price': grpc.unary_unary_rpc_method_handler(
                    servicer.Price,
                    request_deserializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryPriceRequest.FromString,
                    response_serializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryPriceResponse.SerializeToString,
            ),
            'Prices': grpc.unary_unary_rpc_method_handler(
                    servicer.Prices,
                    request_deserializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryPricesRequest.FromString,
                    response_serializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryPricesResponse.SerializeToString,
            ),
            'Params': grpc.unary_unary_rpc_method_handler(
                    servicer.Params,
                    request_deserializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryParamsRequest.FromString,
                    response_serializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryParamsResponse.SerializeToString,
            ),
            'Aggregators': grpc.unary_unary_rpc_method_handler(
                    servicer.Aggregators,
                    request_deserializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryAggregatorsRequest.FromString,
                    response_serializer=marginx_dot_oracle_dot_v1_dot_query__pb2.QueryAggregatorsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marginx.oracle.v1.Query', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Query(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Markets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/marginx.oracle.v1.Query/Markets',
            marginx_dot_oracle_dot_v1_dot_query__pb2.QueryMarketsRequest.SerializeToString,
            marginx_dot_oracle_dot_v1_dot_query__pb2.QueryMarketsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Market(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/marginx.oracle.v1.Query/Market',
            marginx_dot_oracle_dot_v1_dot_query__pb2.QueryMarketRequest.SerializeToString,
            marginx_dot_oracle_dot_v1_dot_query__pb2.QueryMarketResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Price(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/marginx.oracle.v1.Query/Price',
            marginx_dot_oracle_dot_v1_dot_query__pb2.QueryPriceRequest.SerializeToString,
            marginx_dot_oracle_dot_v1_dot_query__pb2.QueryPriceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Prices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/marginx.oracle.v1.Query/Prices',
            marginx_dot_oracle_dot_v1_dot_query__pb2.QueryPricesRequest.SerializeToString,
            marginx_dot_oracle_dot_v1_dot_query__pb2.QueryPricesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Params(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/marginx.oracle.v1.Query/Params',
            marginx_dot_oracle_dot_v1_dot_query__pb2.QueryParamsRequest.SerializeToString,
            marginx_dot_oracle_dot_v1_dot_query__pb2.QueryParamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Aggregators(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/marginx.oracle.v1.Query/Aggregators',
            marginx_dot_oracle_dot_v1_dot_query__pb2.QueryAggregatorsRequest.SerializeToString,
            marginx_dot_oracle_dot_v1_dot_query__pb2.QueryAggregatorsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
