# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from fxsdk.x.fx.gov.v1 import tx_pb2 as fx_dot_gov_dot_v1_dot_tx__pb2


class MsgStub(object):
    """Msg defines the fx/x/gov Msg service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateParams = channel.unary_unary(
                '/fx.gov.v1.Msg/UpdateParams',
                request_serializer=fx_dot_gov_dot_v1_dot_tx__pb2.MsgUpdateParams.SerializeToString,
                response_deserializer=fx_dot_gov_dot_v1_dot_tx__pb2.MsgUpdateParamsResponse.FromString,
                )
        self.UpdateEGFParams = channel.unary_unary(
                '/fx.gov.v1.Msg/UpdateEGFParams',
                request_serializer=fx_dot_gov_dot_v1_dot_tx__pb2.MsgUpdateEGFParams.SerializeToString,
                response_deserializer=fx_dot_gov_dot_v1_dot_tx__pb2.MsgUpdateEGFParamsResponse.FromString,
                )


class MsgServicer(object):
    """Msg defines the fx/x/gov Msg service.
    """

    def UpdateParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEGFParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateParams': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateParams,
                    request_deserializer=fx_dot_gov_dot_v1_dot_tx__pb2.MsgUpdateParams.FromString,
                    response_serializer=fx_dot_gov_dot_v1_dot_tx__pb2.MsgUpdateParamsResponse.SerializeToString,
            ),
            'UpdateEGFParams': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEGFParams,
                    request_deserializer=fx_dot_gov_dot_v1_dot_tx__pb2.MsgUpdateEGFParams.FromString,
                    response_serializer=fx_dot_gov_dot_v1_dot_tx__pb2.MsgUpdateEGFParamsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fx.gov.v1.Msg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Msg(object):
    """Msg defines the fx/x/gov Msg service.
    """

    @staticmethod
    def UpdateParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fx.gov.v1.Msg/UpdateParams',
            fx_dot_gov_dot_v1_dot_tx__pb2.MsgUpdateParams.SerializeToString,
            fx_dot_gov_dot_v1_dot_tx__pb2.MsgUpdateParamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateEGFParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fx.gov.v1.Msg/UpdateEGFParams',
            fx_dot_gov_dot_v1_dot_tx__pb2.MsgUpdateEGFParams.SerializeToString,
            fx_dot_gov_dot_v1_dot_tx__pb2.MsgUpdateEGFParamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
