# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fx/crosschain/v1/genesis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from x.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from x.fx.crosschain.v1 import types_pb2 as fx_dot_crosschain_dot_v1_dot_types__pb2
from x.fx.crosschain.v1 import tx_pb2 as fx_dot_crosschain_dot_v1_dot_tx__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x66x/crosschain/v1/genesis.proto\x12\x18\x66x.gravity.crosschain.v1\x1a\x14gogoproto/gogo.proto\x1a\x1c\x66x/crosschain/v1/types.proto\x1a\x19\x66x/crosschain/v1/tx.proto\"\xf4\x05\n\x0cGenesisState\x12\x36\n\x06params\x18\x01 \x01(\x0b\x32 .fx.gravity.crosschain.v1.ParamsB\x04\xc8\xde\x1f\x00\x12!\n\x19last_observed_event_nonce\x18\x02 \x01(\x04\x12[\n\x1alast_observed_block_height\x18\x03 \x01(\x0b\x32\x31.fx.gravity.crosschain.v1.LastObservedBlockHeightB\x04\xc8\xde\x1f\x00\x12\x37\n\x07oracles\x18\x04 \x03(\x0b\x32 .fx.gravity.crosschain.v1.OracleB\x04\xc8\xde\x1f\x00\x12>\n\x0boracle_sets\x18\x05 \x03(\x0b\x32#.fx.gravity.crosschain.v1.OracleSetB\x04\xc8\xde\x1f\x00\x12\x42\n\rbridge_tokens\x18\x06 \x03(\x0b\x32%.fx.gravity.crosschain.v1.BridgeTokenB\x04\xc8\xde\x1f\x00\x12O\n\x13unbatched_transfers\x18\x07 \x03(\x0b\x32,.fx.gravity.crosschain.v1.OutgoingTransferTxB\x04\xc8\xde\x1f\x00\x12@\n\x07\x62\x61tches\x18\x08 \x03(\x0b\x32).fx.gravity.crosschain.v1.OutgoingTxBatchB\x04\xc8\xde\x1f\x00\x12P\n\x13oracle_set_confirms\x18\t \x03(\x0b\x32-.fx.gravity.crosschain.v1.MsgOracleSetConfirmB\x04\xc8\xde\x1f\x00\x12G\n\x0e\x62\x61tch_confirms\x18\n \x03(\x0b\x32).fx.gravity.crosschain.v1.MsgConfirmBatchB\x04\xc8\xde\x1f\x00\x12\x41\n\x0c\x61ttestations\x18\x0b \x03(\x0b\x32%.fx.gravity.crosschain.v1.AttestationB\x04\xc8\xde\x1f\x00\x42\x31Z/github.com/functionx/fx-core/x/crosschain/typesb\x06proto3')



_GENESISSTATE = DESCRIPTOR.message_types_by_name['GenesisState']
GenesisState = _reflection.GeneratedProtocolMessageType('GenesisState', (_message.Message,), {
  'DESCRIPTOR' : _GENESISSTATE,
  '__module__' : 'fx.crosschain.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:fx.gravity.crosschain.v1.GenesisState)
  })
_sym_db.RegisterMessage(GenesisState)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/functionx/fx-core/x/crosschain/types'
  _GENESISSTATE.fields_by_name['params']._options = None
  _GENESISSTATE.fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _GENESISSTATE.fields_by_name['last_observed_block_height']._options = None
  _GENESISSTATE.fields_by_name['last_observed_block_height']._serialized_options = b'\310\336\037\000'
  _GENESISSTATE.fields_by_name['oracles']._options = None
  _GENESISSTATE.fields_by_name['oracles']._serialized_options = b'\310\336\037\000'
  _GENESISSTATE.fields_by_name['oracle_sets']._options = None
  _GENESISSTATE.fields_by_name['oracle_sets']._serialized_options = b'\310\336\037\000'
  _GENESISSTATE.fields_by_name['bridge_tokens']._options = None
  _GENESISSTATE.fields_by_name['bridge_tokens']._serialized_options = b'\310\336\037\000'
  _GENESISSTATE.fields_by_name['unbatched_transfers']._options = None
  _GENESISSTATE.fields_by_name['unbatched_transfers']._serialized_options = b'\310\336\037\000'
  _GENESISSTATE.fields_by_name['batches']._options = None
  _GENESISSTATE.fields_by_name['batches']._serialized_options = b'\310\336\037\000'
  _GENESISSTATE.fields_by_name['oracle_set_confirms']._options = None
  _GENESISSTATE.fields_by_name['oracle_set_confirms']._serialized_options = b'\310\336\037\000'
  _GENESISSTATE.fields_by_name['batch_confirms']._options = None
  _GENESISSTATE.fields_by_name['batch_confirms']._serialized_options = b'\310\336\037\000'
  _GENESISSTATE.fields_by_name['attestations']._options = None
  _GENESISSTATE.fields_by_name['attestations']._serialized_options = b'\310\336\037\000'
  _GENESISSTATE._serialized_start=140
  _GENESISSTATE._serialized_end=896
# @@protoc_insertion_point(module_scope)
