# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fx/legacy/base/v1/query.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from x.cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from x.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from x.google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x66x/legacy/base/v1/query.proto\x12\nfx.base.v1\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\"\x14\n\x12GetGasPriceRequest\"\x8b\x01\n\x13GetGasPriceResponse\x12t\n\ngas_prices\x18\x01 \x03(\x0b\x32\x19.cosmos.base.v1beta1.CoinBE\xc8\xde\x1f\x00\xaa\xdf\x1f(github.com/cosmos/cosmos-sdk/types.Coins\xf2\xde\x1f\x11yaml:\"gas_prices\"2v\n\x05Query\x12m\n\x0bGetGasPrice\x12\x1e.fx.base.v1.GetGasPriceRequest\x1a\x1f.fx.base.v1.GetGasPriceResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/fx/base/v1/gas_priceB=Z;github.com/functionx/fx-core/server/grpc/gasprice/legacy/v2b\x06proto3')



_GETGASPRICEREQUEST = DESCRIPTOR.message_types_by_name['GetGasPriceRequest']
_GETGASPRICERESPONSE = DESCRIPTOR.message_types_by_name['GetGasPriceResponse']
GetGasPriceRequest = _reflection.GeneratedProtocolMessageType('GetGasPriceRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETGASPRICEREQUEST,
  '__module__' : 'fx.legacy.base.v1.query_pb2'
  # @@protoc_insertion_point(class_scope:fx.base.v1.GetGasPriceRequest)
  })
_sym_db.RegisterMessage(GetGasPriceRequest)

GetGasPriceResponse = _reflection.GeneratedProtocolMessageType('GetGasPriceResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETGASPRICERESPONSE,
  '__module__' : 'fx.legacy.base.v1.query_pb2'
  # @@protoc_insertion_point(class_scope:fx.base.v1.GetGasPriceResponse)
  })
_sym_db.RegisterMessage(GetGasPriceResponse)

_QUERY = DESCRIPTOR.services_by_name['Query']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z;github.com/functionx/fx-core/server/grpc/gasprice/legacy/v2'
  _GETGASPRICERESPONSE.fields_by_name['gas_prices']._options = None
  _GETGASPRICERESPONSE.fields_by_name['gas_prices']._serialized_options = b'\310\336\037\000\252\337\037(github.com/cosmos/cosmos-sdk/types.Coins\362\336\037\021yaml:\"gas_prices\"'
  _QUERY.methods_by_name['GetGasPrice']._options = None
  _QUERY.methods_by_name['GetGasPrice']._serialized_options = b'\202\323\344\223\002\027\022\025/fx/base/v1/gas_price'
  _GETGASPRICEREQUEST._serialized_start=129
  _GETGASPRICEREQUEST._serialized_end=149
  _GETGASPRICERESPONSE._serialized_start=152
  _GETGASPRICERESPONSE._serialized_end=291
  _QUERY._serialized_start=293
  _QUERY._serialized_end=411
# @@protoc_insertion_point(module_scope)
