# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fx/gravity/v1/ethereum_signer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from x.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#fx/gravity/v1/ethereum_signer.proto\x12\rfx.gravity.v1\x1a\x14gogoproto/gogo.proto*\x95\x01\n\x08SignType\x12\x19\n\x15SIGN_TYPE_UNSPECIFIED\x10\x00\x12\x32\n.SIGN_TYPE_ORCHESTRATOR_SIGNED_MULTI_SIG_UPDATE\x10\x01\x12\x30\n,SIGN_TYPE_ORCHESTRATOR_SIGNED_WITHDRAW_BATCH\x10\x02\x1a\x08\x88\xa3\x1e\x00\xa8\xa4\x1e\x00\x42.Z,github.com/functionx/fx-core/x/gravity/typesb\x06proto3')

_SIGNTYPE = DESCRIPTOR.enum_types_by_name['SignType']
SignType = enum_type_wrapper.EnumTypeWrapper(_SIGNTYPE)
SIGN_TYPE_UNSPECIFIED = 0
SIGN_TYPE_ORCHESTRATOR_SIGNED_MULTI_SIG_UPDATE = 1
SIGN_TYPE_ORCHESTRATOR_SIGNED_WITHDRAW_BATCH = 2


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,github.com/functionx/fx-core/x/gravity/types'
  _SIGNTYPE._options = None
  _SIGNTYPE._serialized_options = b'\210\243\036\000\250\244\036\000'
  _SIGNTYPE._serialized_start=77
  _SIGNTYPE._serialized_end=226
# @@protoc_insertion_point(module_scope)
