# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/slashing/v1beta1/query.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fxsdk.x.cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
from fxsdk.x.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from fxsdk.x.cosmos.slashing.v1beta1 import slashing_pb2 as cosmos_dot_slashing_dot_v1beta1_dot_slashing__pb2
from fxsdk.x.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#cosmos/slashing/v1beta1/query.proto\x12\x17\x63osmos.slashing.v1beta1\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a&cosmos/slashing/v1beta1/slashing.proto\x1a\x19\x63osmos_proto/cosmos.proto\"\x14\n\x12QueryParamsRequest\"L\n\x13QueryParamsResponse\x12\x35\n\x06params\x18\x01 \x01(\x0b\x32\x1f.cosmos.slashing.v1beta1.ParamsB\x04\xc8\xde\x1f\x00\"I\n\x17QuerySigningInfoRequest\x12.\n\x0c\x63ons_address\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressString\"i\n\x18QuerySigningInfoResponse\x12M\n\x10val_signing_info\x18\x01 \x01(\x0b\x32-.cosmos.slashing.v1beta1.ValidatorSigningInfoB\x04\xc8\xde\x1f\x00\"V\n\x18QuerySigningInfosRequest\x12:\n\npagination\x18\x01 \x01(\x0b\x32&.cosmos.base.query.v1beta1.PageRequest\"\x9b\x01\n\x19QuerySigningInfosResponse\x12\x41\n\x04info\x18\x01 \x03(\x0b\x32-.cosmos.slashing.v1beta1.ValidatorSigningInfoB\x04\xc8\xde\x1f\x00\x12;\n\npagination\x18\x02 \x01(\x0b\x32\'.cosmos.base.query.v1beta1.PageResponse2\xf2\x03\n\x05Query\x12\x8c\x01\n\x06Params\x12+.cosmos.slashing.v1beta1.QueryParamsRequest\x1a,.cosmos.slashing.v1beta1.QueryParamsResponse\"\'\x82\xd3\xe4\x93\x02!\x12\x1f/cosmos/slashing/v1beta1/params\x12\xb1\x01\n\x0bSigningInfo\x12\x30.cosmos.slashing.v1beta1.QuerySigningInfoRequest\x1a\x31.cosmos.slashing.v1beta1.QuerySigningInfoResponse\"=\x82\xd3\xe4\x93\x02\x37\x12\x35/cosmos/slashing/v1beta1/signing_infos/{cons_address}\x12\xa5\x01\n\x0cSigningInfos\x12\x31.cosmos.slashing.v1beta1.QuerySigningInfosRequest\x1a\x32.cosmos.slashing.v1beta1.QuerySigningInfosResponse\".\x82\xd3\xe4\x93\x02(\x12&/cosmos/slashing/v1beta1/signing_infosB/Z-github.com/cosmos/cosmos-sdk/x/slashing/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cosmos.slashing.v1beta1.query_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-github.com/cosmos/cosmos-sdk/x/slashing/types'
  _QUERYPARAMSRESPONSE.fields_by_name['params']._options = None
  _QUERYPARAMSRESPONSE.fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _QUERYSIGNINGINFOREQUEST.fields_by_name['cons_address']._options = None
  _QUERYSIGNINGINFOREQUEST.fields_by_name['cons_address']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _QUERYSIGNINGINFORESPONSE.fields_by_name['val_signing_info']._options = None
  _QUERYSIGNINGINFORESPONSE.fields_by_name['val_signing_info']._serialized_options = b'\310\336\037\000'
  _QUERYSIGNINGINFOSRESPONSE.fields_by_name['info']._options = None
  _QUERYSIGNINGINFOSRESPONSE.fields_by_name['info']._serialized_options = b'\310\336\037\000'
  _QUERY.methods_by_name['Params']._options = None
  _QUERY.methods_by_name['Params']._serialized_options = b'\202\323\344\223\002!\022\037/cosmos/slashing/v1beta1/params'
  _QUERY.methods_by_name['SigningInfo']._options = None
  _QUERY.methods_by_name['SigningInfo']._serialized_options = b'\202\323\344\223\0027\0225/cosmos/slashing/v1beta1/signing_infos/{cons_address}'
  _QUERY.methods_by_name['SigningInfos']._options = None
  _QUERY.methods_by_name['SigningInfos']._serialized_options = b'\202\323\344\223\002(\022&/cosmos/slashing/v1beta1/signing_infos'
  _globals['_QUERYPARAMSREQUEST']._serialized_start=227
  _globals['_QUERYPARAMSREQUEST']._serialized_end=247
  _globals['_QUERYPARAMSRESPONSE']._serialized_start=249
  _globals['_QUERYPARAMSRESPONSE']._serialized_end=325
  _globals['_QUERYSIGNINGINFOREQUEST']._serialized_start=327
  _globals['_QUERYSIGNINGINFOREQUEST']._serialized_end=400
  _globals['_QUERYSIGNINGINFORESPONSE']._serialized_start=402
  _globals['_QUERYSIGNINGINFORESPONSE']._serialized_end=507
  _globals['_QUERYSIGNINGINFOSREQUEST']._serialized_start=509
  _globals['_QUERYSIGNINGINFOSREQUEST']._serialized_end=595
  _globals['_QUERYSIGNINGINFOSRESPONSE']._serialized_start=598
  _globals['_QUERYSIGNINGINFOSRESPONSE']._serialized_end=753
  _globals['_QUERY']._serialized_start=756
  _globals['_QUERY']._serialized_end=1254
# @@protoc_insertion_point(module_scope)
